package com.eltech.study.service;


/**
* MyApp/ServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/����/IdeaProjects/tcorba/src/com/eltech/study/app.idl
* 26 ������� 2014 �. 0:52:51 MSK
*/

public interface ServiceOperations 
{
  String doTheThing (String inParam);
  void shutdown ();
} // interface ServiceOperations
