package com.eltech.study.service;


/**
* MyApp/Service.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/����/IdeaProjects/tcorba/src/com/eltech/study/app.idl
* 26 ������� 2014 �. 0:52:51 MSK
*/

public interface Service extends ServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Service
